kind: pipeline
type: docker
name: vixuals

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone --single-branch --branch $DRONE_SOURCE_BRANCH --depth=1 $DRONE_GIT_HTTP_URL .

- name: build-dev
  image: node:alpine
  commands:
  - npm install
  - npm run build
  when:
    branch:
    - main
    event:
    - push
    - pull_request

- name: build
  image: node:alpine
  commands:
  - npm install
  - npm run build
  when:
    branch:
    - main
    event:
    - tag

- name: publish-dev
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: paulwrubel/vixuals
    tags:
    - dev
  when:
    branch:
    - main
    event:
    - push

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: paulwrubel/vixuals
    tags:
    - latest
  when:
    branch:
    - main
    event:
    - tag
